### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by Dekania** [Pepijn98/CSP-Discord#1]
after attempting to install this, i'm met with a circular dependency error and after tracing the error, it comes back with this:

```
Error: Cannot find module 'discord-rich-presence'
Require stack:
- D:\Downloads\CSP-Discord-master\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\Downloads\CSP-Discord-master\index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Downloads\\CSP-Discord-master\\index.js' ]
}
```

edit:

the service does install despite the circular dependency, but it never starts even after a full restart, starting the service manually, or reopening clip studio paint

**Comment by rahadiannorman** [comment]
I think I had the same issues, just opened the new issue/thread, is yours fixed now?

**Comment by Dekania** [comment]
no luck, sadly

**Comment by Pepijn98** [comment]
Sorry guys, I took a long break from any personal programming stuff. I can take a look at both #1 and #2 next week if y'all still need it.

**Comment by rahadiannorman** [comment]
> Sorry guys, I took a long break from any personal programming stuff. I can take a look at both #1 and #2 next week if y'all still need it.

Oh hi! I still need it, I'll be looking forward from your updates, thank you so muchh!

**Comment by Pepijn98** [comment]
Hello, updated some stuff. Seems to be working now so if y'all can download the new version and try it out.
You can remove `qckwinsvc` from the global npm using `npm uninstall -g qckwinsvc` since that one is broken.
There's an updated version `qckwinsvc2`, I updated the [README](https://github.com/Pepijn98/CSP-Discord#readme) with the new instructions to get it running.

**Comment by Pepijn98** [comment]
Made another little update so you don't have to install qckwinsvc2 at all. Instructions are updated in the [README](https://github.com/Pepijn98/CSP-Discord#usage). Hope this fixes most of the issues.

**Comment by rahadiannorman** [comment]
> Made another little update so you don't have to install qckwinsvc2 at all. Instructions are updated in the [README](https://github.com/Pepijn98/CSP-Discord#usage). Hope this fixes most of the issues.

![image](https://github.com/Pepijn98/CSP-Discord/assets/30531877/b1839d4f-e190-480c-88ff-af83985642ab)

It seems working fine, but I had issues installing it on root file of the CSP and I don't want to take risk of it getting similar error again, thank you so much for you time.

**Comment by Dekania** [comment]
hi, apologies for the late reply!
![image](https://github.com/Pepijn98/CSP-Discord/assets/29765817/2b6c99dd-a9ed-42af-a531-3d31722a7024)
it worked perfectly! thank you so much!

**Comment by Pepijn98** [comment]
Awesome, closing #1 and #2
