### ISSUE TITLE
It doesn't work after reinstallation.

### ISSUE THREAD

**Issue by rahadiannorman** [Pepijn98/CSP-Discord#2]
I ran and installed the repo on Download folder which unfortunately I had to moved it into `"C:\Program Files\CELSYS\CLIP STUDIO 1.5\CLIP STUDIO PAINT\PlugIn\CSP-Discord_RPC"` after moved it and reopen my Clip Studio Paint, it only shows me this:

![image](https://github.com/Pepijn98/CSP-Discord/assets/30531877/13e34ad7-4432-43a0-9b83-e0e5bc3c60ef)

So I tried reinstalling which again I had to delete the files and the services via Registry Editor too then refollowing the instruction until I ran the `index.js` instruction and it gives me this message: 

```
$ qckwinsvc --name "ClipStudioPaint" --description "Clip Studio Paint Discord Presence" --script "C:\Program Files\CELSYS\CLIP STUDIO 1.5\CLIP STUDIO PAINT\PlugIn\CSP-Discord_RPC\index.js" --startImmediately
(node:21228) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Service installed.
Service started.
```

The result remains persist as it only worked for the first time before I'm reinstalling it.

I also wanted to thank you for making this CSP Discord RPC, I hope CELSYS had their own Discord RPC without needing to something like this, I have no Idea about codes/programming, I just learned today assisted by Bing Co-Pilot.

**Comment by Pepijn98** [comment]
Fixed #1
